<a href="https://colab.research.google.com/github/aa4758/pytorch_tutorial/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
- A torch. Tensor is a multi-dimensional matrix containing elements of a single data type
- Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's)
- default data type of float32
- More suitable for deep learning than a numpy array

In [2]:
import torch
import numpy as np

# LIST

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAY

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.15724309, 0.35015178, 0.08302452, 0.82168694],
       [0.77647479, 0.40121278, 0.05355552, 0.80018768],
       [0.05723351, 0.72042218, 0.31586861, 0.12597122]])

In [5]:
np1.dtype

dtype('float64')

# TENSORS

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.1605,  2.5440,  1.0501, -1.7522],
        [ 0.0856,  1.4537, -0.3146,  0.5501],
        [-0.9160,  0.8065,  1.3874,  0.0162]])

In [8]:
tensors_3d = torch.zeros(2, 3, 4)
tensors_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
tensors_4d = torch.randn(2, 3, 4, 5)
tensors_4d

tensor([[[[ 3.2722e-01, -7.9852e-01,  1.7539e-01,  7.8093e-02,  5.4081e-01],
          [ 5.4026e-01, -6.0276e-01, -5.6281e-02,  6.7780e-01, -4.4271e-02],
          [ 1.3981e+00,  1.0093e+00,  7.9156e-02, -8.6237e-01, -9.3252e-01],
          [-4.1258e-01, -4.7703e-01, -1.1376e+00,  6.4418e-01,  1.4859e+00]],

         [[ 6.3062e-01,  4.7003e-01,  6.4234e-01,  3.4438e-01,  2.9648e-01],
          [-1.8027e+00,  1.9877e+00,  5.9078e-02,  1.9341e+00, -5.3873e-01],
          [-1.0408e+00,  1.4094e+00, -3.5395e-01,  1.4385e+00,  1.0387e+00],
          [ 1.1385e-01,  1.9445e+00, -7.3415e-01, -2.0003e+00, -2.9800e-03]],

         [[ 2.0306e+00, -4.7440e-01,  1.9005e+00, -7.6823e-01,  7.3010e-01],
          [-1.2511e+00, -3.6350e-01, -1.0687e+00, -8.8091e-01, -2.5108e-01],
          [-1.0298e+00,  4.0153e-01, -7.0013e-01,  1.0744e+00, -1.7539e+00],
          [ 1.6483e-01,  8.2353e-01, -1.4044e-01,  3.3219e-01, -9.7544e-01]]],


        [[[ 1.0381e+00,  7.7807e-01,  7.7033e-01,  4.7164e-01,  3.23

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1572, 0.3502, 0.0830, 0.8217],
        [0.7765, 0.4012, 0.0536, 0.8002],
        [0.0572, 0.7204, 0.3159, 0.1260]], dtype=torch.float64)